steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "build/client/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/hello-client",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/hello-client"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "build/server/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/hello-server",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/hello-server"]
