// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pb/run.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunClient is the client API for Run service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type runClient struct {
	cc grpc.ClientConnInterface
}

func NewRunClient(cc grpc.ClientConnInterface) RunClient {
	return &runClient{cc}
}

func (c *runClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/pb.Run/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunServer is the server API for Run service.
// All implementations must embed UnimplementedRunServer
// for forward compatibility
type RunServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedRunServer()
}

// UnimplementedRunServer must be embedded to have forward compatible implementations.
type UnimplementedRunServer struct {
}

func (UnimplementedRunServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedRunServer) mustEmbedUnimplementedRunServer() {}

// UnsafeRunServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunServer will
// result in compilation errors.
type UnsafeRunServer interface {
	mustEmbedUnimplementedRunServer()
}

func RegisterRunServer(s grpc.ServiceRegistrar, srv RunServer) {
	s.RegisterService(&Run_ServiceDesc, srv)
}

func _Run_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Run/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Run_ServiceDesc is the grpc.ServiceDesc for Run service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Run_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Run",
	HandlerType: (*RunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Run_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/run.proto",
}
